### ISSUE TITLE
do i need pipewire?

### ISSUE THREAD

**Issue by Dr-Deep** [adgsenpai/LinuxDolbyAtmos#2]
┌─[panxc@voidlab]-[~/dolby]
└──╼[$]> easyeffects 

(easyeffects:22189): Adwaita-WARNING **: 21:41:06.376: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.
[E] pw.loop [loop.c:86 pw_loop_new()] 0x563e575a3820: can't make support.system handle: Datei oder Verzeichnis nicht gefunden

(easyeffects:22189): easyeffects-ERROR **: 21:41:06.392: pipe_manager: could not create PipeWire loop
Trace/Breakpoint ausgelöst

**Comment by adgsenpai** [comment]
> ┌─[panxc@voidlab]-[~/dolby] └──╼[$]> easyeffects
> 
> (easyeffects:22189): Adwaita-WARNING **: 21:41:06.376: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead. [E] pw.loop [loop.c:86 pw_loop_new()] 0x563e575a3820: can't make support.system handle: Datei oder Verzeichnis nicht gefunden
> 
> (easyeffects:22189): easyeffects-ERROR **: 21:41:06.392: pipe_manager: could not create PipeWire loop Trace/Breakpoint ausgelöst

I originally did this based on Ubuntu Distro and also Kali Linux Distro.
From what I am thinking you are on Arch?

you could try installing this package here
```
pipewire-pulse
```

you could read up here also for more info
https://wiki.archlinux.org/title/PipeWire


let me know if it works! 
If you have already countered the issue feel free to share your solution here for others. 

Then I will close issue.
