### ISSUE TITLE
Real 3d audio?

### ISSUE THREAD

**Issue by sequeirayeslin** [adgsenpai/LinuxDolbyAtmos#4]
Is this actual dolby atmos 3d audio? It looks to me like this is just a simple FIR filter

**Comment by adgsenpai** [comment]
This is a filter in a way it sounds like Dolby Atmos but not the real thing. I'd reckon its around 70-80% sounds like the real Dolby Atmos Audio.

On Windows, Android i got the real Dolby Atmos so far on Linux doesn't seem it has been out.

Feel Free to ask any other additional questions!

**Comment by sequeirayeslin** [comment]
Oh ok. Where did you get the impulse response? I dont think a simple FIR filter is the same as dolby atmos. Dolby atmos is 3d audio. You need to have access to each "object" in the 3d space as a seperate signal, and filter them out via 2 impulse responses which depend on the location of the object. You cannot achieve the effect by just filtering out stereo via a single FIR filter, it would take multiple filters, access to each individual sound in the mix as a seperate signal, special kind of processing for moving objects (according to what i found in my experimentation in matlab). Getting 3d audio to work is quite complicated and requires "cooperation" from the audio you are trying to 3d-fy (the audio needs to have special information related to 3d audio.

**Comment by sequeirayeslin** [comment]
Why did you call it dolby atmos?

**Comment by sequeirayeslin** [comment]
This is just an equalizer with the settings hardcoded

**Comment by adgsenpai** [comment]
I have found this equalizer reading an article from the internet. The article author may or not created the equalizer . My purpose of this repo is to provide information towards a guide better than the article and also enable people to get a somewhat better sound experience towards sound on Linux.

Why i called it Linux Dolby Atmos?
- This plugin somewhat provides a similar experience to it.

**Comment by sequeirayeslin** [comment]
I dont think its approriate to call this dolby atmos. Simple filtering vs 3d audio: 2 very different things. If this were a 3rd party implementation of 3d audio that read dolby atmos metadata and generated true 3d audio, then i get it. But this isnt it, its misleading

**Comment by sequeirayeslin** [comment]
Cool. I dont really think it should be called dolby atmos, but its fine.

**Comment by akash-258** [comment]
>I dont really think it should be called dolby atmos
Kind of agree, name it similar, but naming it exactly this ?

**Comment by adgsenpai** [comment]
> >I dont really think it should be called dolby atmos
> Kind of agree, name it similar, but naming it exactly this ?

What do you think it should be named then?

**Comment by sequeirayeslin** [comment]
I dont think it should be named anything similar either. It is just a preset for the equaliser in easyeffects. "My preferred equaliser config" is very accurate.

**Comment by sequeirayeslin** [comment]
The name is actually quite misleading. The repo's content has no relation to dolby atmos

**Comment by adgsenpai** [comment]
> I dont think it should be named anything similar either. It is just a preset for the equaliser in easyeffects. "My preferred equaliser config" is very accurate.

Cool, thanks for your knowledgeable insights @akash-258 @sequeirayeslin I will rename the repo and also the Readme to remove all misleading Dolby Atmos text.

**Comment by akash-258** [comment]
You dont have to rename it as "my config" or something. Create whatever unique name you like, but what also effectively signifies the content of your repo.
