### ISSUE TITLE
EasyEffects looks completely different from the provided screenshots

### ISSUE THREAD

**Issue by alba4k** [adgsenpai/LinuxDolbyAtmos#5]
As the title says, easy effects looks completely different on my machine than it does in your screeshots.

I had this same problem on an old machine too.

![immagine](https://user-images.githubusercontent.com/84153269/205726210-3767cc97-a55c-4472-b804-b43b8efcddec.png)

**Comment by adgsenpai** [comment]
Give me a few days, Will install Linux on my machine and reproduce with new screenshots!

- For now you can try adding an effect and see if it works. Bit busy at the moment with work and studies. When free will update screen shots.

Best Regards
Mr AD Govindasamy

**Comment by adgsenpai** [comment]
> As the title says, easy effects looks completely different on my machine than it does in your screeshots.
> 
> I had this same problem on an old machine too.
> 
> ![immagine](https://user-images.githubusercontent.com/84153269/205726210-3767cc97-a55c-4472-b804-b43b8efcddec.png)

Note on Ubuntu now i have installed `PulseEffects` like this 

![image](https://user-images.githubusercontent.com/45560312/205731208-121bd1b6-a1cc-471e-b2d7-e4980add9d8a.png)

I will uninstall it now, and get EasyEffects using the `FlatHub` Channel to replicate your issue

**Comment by adgsenpai** [comment]
1. Steps to Follow 
![image](https://user-images.githubusercontent.com/45560312/205732912-e87908a4-310e-43c2-b74f-7bfedd6fd861.png)

Click `Add Effect` in Effects Tab as in Image

2. Select `Convolver and hit the + icon`
![image](https://user-images.githubusercontent.com/45560312/205732987-27004488-056f-492f-8e7d-301a201e79db.png)

3. `Click` `Import Impulse` 

![image](https://user-images.githubusercontent.com/45560312/205733115-1f90fcf0-3aff-411e-ae6f-eab0024ab7b7.png)

4. Import `SoundUpgrade.irs`

![image](https://user-images.githubusercontent.com/45560312/205733352-bd921076-388a-414c-b8cf-8d69f98a80bc.png)

5. Click `Impulses` Again
![image](https://user-images.githubusercontent.com/45560312/205733449-7b165d3e-0ee7-4f3f-8346-a504874fb7b2.png)

6. Click `Load`

![image](https://user-images.githubusercontent.com/45560312/205733766-d68bb469-735e-4ec1-b970-99e3e01ef0c2.png)

Should work let me know if it works for you!

Note I never test any audio on the system as I'm running a VM.
